name: Auto Tag

on:
  push:
    branches:
      - main
    # Ignore changes to documentation/workflow files to avoid unnecessary tagging
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          # The action uses these patterns in commit messages to determine the bump
          # #major, #minor, #patch
